#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc rule -a Lxappearance state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# xsetroot -cursor_name left_ptr &
feh --recursive --randomize --bg-fill ~/Pictures/wallpapers/
